services:
  servera:
    build: .
    container_name: jlab-serverA
    ports:
      - '8888:8888'
    command: >
      jupyter server --no-browser
      --ip=0.0.0.0
      --port=8888
      --ServerApp.token=abc123
      --ServerApp.allow_origin=*

  serverb:
    build: .
    container_name: jlab-serverB
    ports:
      - '8889:8889'
    command: >
      jupyter lab --no-browser
      --ip=0.0.0.0
      --port=8889
      --ServerApp.token=abc123
